<?php
$apps = is_array($apps ?? null) ? $apps : [];
$error = session()->getFlashdata('error');
$success = session()->getFlashdata('success');
$footerMessage = $error ?: $success;
$footerStatus = $error ? 'error' : ($success ? 'success' : '');
?>
<div class="col-12 apps-admin" data-footer-message="<?= esc((string) ($footerMessage ?? ''), 'attr') ?>" data-footer-status="<?= esc($footerStatus, 'attr') ?>">
<header class="apps-title"><div><span>ADMINISTRAÇÃO</span><h1>Aplicativos</h1></div><button type="button" data-bs-toggle="modal" data-bs-target="#create-app-modal"><i class="bi bi-plus-lg"></i> Novo aplicativo</button></header>
<div class="apps-stats"><article><span>APLICATIVOS CADASTRADOS</span><strong><?= count($apps) ?></strong></article><article><span>CONTROLE DE ACESSO</span><strong class="status-active">ATIVO</strong></article></div>
<?php if ($error): ?><div class="alert alert-danger bg-dark border-danger text-danger"><?= esc($error) ?></div><?php elseif ($success): ?><div class="alert alert-success bg-dark border-success text-success"><?= esc($success) ?></div><?php endif; ?>
<section class="apps-panel"><div class="table-responsive"><table class="table table-dark table-hover align-middle mb-0"><thead><tr><th>Aplicativo</th><th>Ícone</th><th>URL</th><th>Nível</th><th class="text-end">Ações</th></tr></thead><tbody>
<?php if ($apps === []): ?><tr><td colspan="5" class="apps-empty">Nenhum aplicativo cadastrado.</td></tr><?php endif; ?>
<?php foreach ($apps as $app): ?><tr><td><strong><?= esc($app['name']) ?></strong></td><td><i class="bi <?= esc($app['icon'], 'attr') ?> app-icon"></i> <code><?= esc($app['icon']) ?></code></td><td><a href="<?= esc($app['url'], 'attr') ?>" target="_blank" rel="noopener noreferrer"><?= esc($app['url']) ?></a></td><td><span class="access-badge"><?= esc($app['access_level']) ?></span></td><td><div class="app-actions"><button type="button" data-bs-toggle="modal" data-bs-target="#edit-app-<?= $app['id'] ?>"><i class="bi bi-pencil"></i> Editar</button><form action="<?= site_url('dashboard/admin/apps/' . $app['id'] . '/delete') ?>" method="post" data-confirm-delete="Deseja excluir este aplicativo?"><?= csrf_field() ?><button class="delete" type="submit"><i class="bi bi-trash3"></i> Excluir</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div></section>
</div>

<div class="modal fade" id="create-app-modal" tabindex="-1" aria-labelledby="create-app-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content admin-modal"><form action="<?= site_url('dashboard/admin/apps') ?>" method="post"><?= csrf_field() ?><div class="modal-header"><h2 class="modal-title fs-5" id="create-app-title">Novo aplicativo</h2><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><?= view('dashboard/admin/app_form', ['app' => null, 'prefix' => 'create']) ?></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-info">Cadastrar</button></div></form></div></div></div>

<?php foreach ($apps as $app): ?><div class="modal fade" id="edit-app-<?= $app['id'] ?>" tabindex="-1" aria-labelledby="edit-app-title-<?= $app['id'] ?>" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content admin-modal"><form action="<?= site_url('dashboard/admin/apps/' . $app['id'] . '/update') ?>" method="post"><?= csrf_field() ?><div class="modal-header"><h2 class="modal-title fs-5" id="edit-app-title-<?= $app['id'] ?>">Editar aplicativo</h2><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><?= view('dashboard/admin/app_form', ['app' => $app, 'prefix' => 'edit-' . $app['id']]) ?></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-info">Salvar</button></div></form></div></div></div><?php endforeach; ?>

<style>
.apps-admin{padding:8px 12px 28px}.apps-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px}.apps-title span{color:var(--purple);font-size:10px;letter-spacing:2px}.apps-title h1{margin:4px 0 0;color:#fff;font-size:26px}.apps-title>button{padding:10px 16px;border:1px solid var(--cyan);border-radius:8px;color:#02101a;background:var(--cyan);font-weight:700}.apps-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-bottom:16px}.apps-stats article{padding:14px 16px;border:1px solid #12334a;border-radius:10px;background:#04101c}.apps-stats span{display:block;color:#7193ac;font-size:9px;letter-spacing:1px}.apps-stats strong{display:block;margin-top:5px;color:#fff;font-size:21px}.apps-stats .status-active{color:var(--green);font-size:16px}.apps-panel{border:1px solid #12334a;border-radius:12px;overflow:hidden}.apps-panel .table{--bs-table-bg:#03101b;--bs-table-hover-bg:#062038}.apps-panel th{padding:13px;color:#7193ac;font-size:10px;letter-spacing:1px}.apps-panel td{padding:13px;color:#b9d5e9}.apps-panel a{color:var(--cyan)}.app-icon{margin-right:6px;color:var(--purple);font-size:20px}.access-badge{padding:5px 11px;border-radius:14px;color:var(--orange);background:#ffad1617}.app-actions{display:flex;justify-content:flex-end;gap:8px}.app-actions form{margin:0}.app-actions button{border:0;color:var(--cyan);background:transparent}.app-actions .delete{color:#ff8b80}.apps-empty{padding:45px!important;text-align:center}.admin-modal{border:1px solid #164c70;color:#d7ebf8;background:#04101c}.admin-modal .modal-header,.admin-modal .modal-footer{border-color:#12334a}@media(max-width:700px){.apps-title{align-items:flex-start;gap:12px;flex-direction:column}.apps-stats{grid-template-columns:1fr}}
</style>
